export const keywords = [
    "nextjs developer",
    "fullstack developer",
    "indonesia developer",
    "vann-dev",
    "vann",
    "stevan vincent",
    "react developer",
    "typescript developer",
    "tailwindcss developer",
    "gsap developer",
    "gsap",
    "tailwindcss",
    "typescript",
    "jasa pembuatan website indonesia",
    "fullstack developer di tangerang",
    "fullstack developer di indonesia",
    "developer di indonesia",
    "fullstack developer di alam sutera",
    "fullstack developer di bsd",
    "fullstack developer di bsd city",
    "fullstack developer di serpong",
    "fullstack developer di serpong city",
    "fullstack developer di serpong garden",
    "fullstack developer di serpong garden city",
    "fullstack developer di serpong garden city tangerang",
    "fullstack developer di serpong tangerang",
    "fullstack developer di serpong city tangerang",
    "fullstack developer di serpong garden tangerang",
    "fullstack developer di serpong garden city tangerang",
    "fullstack developer di serpong garden city tangerang banten",
    "fullstack developer di serpong tangerang banten",
    "fullstack developer di serpong city tangerang banten",
    "fullstack developer di serpong garden tangerang banten",
    "frontend developer di alam sutera",
    "frontend developer di bsd",
    "frontend developer di bsd city",
    "frontend developer di serpong",
    "frontend developer di serpong city",
    "frontend developer di serpong garden",
    "frontend developer di serpong garden city",
    "frontend developer di serpong garden city tangerang",
    "frontend developer di serpong tangerang",
    "frontend developer di serpong city tangerang",
    "frontend developer di serpong garden tangerang",
    "frontend developer di serpong garden city tangerang",
    "frontend developer di serpong garden city tangerang banten",
    "frontend developer di serpong tangerang banten",
    "frontend developer di serpong city tangerang banten",
    "frontend developer di serpong garden tangerang banten",
    "backend developer di alam sutera",
    "backend developer di bsd",
    "backend developer di bsd city",
    "backend developer di serpong",
    "backend developer di serpong city",
    "backend developer di serpong garden",
    "backend developer di serpong garden city",
    "backend developer di serpong garden city tangerang",
    "backend developer di serpong tangerang",
    "backend developer di serpong city tangerang",
    "backend developer di serpong garden tangerang",
    "backend developer di serpong garden city tangerang",
    "backend developer di serpong garden city tangerang banten",
    "backend developer di serpong tangerang banten",
    "backend developer di serpong city tangerang banten",
    "backend developer di serpong garden tangerang banten",
    "jasa pembuatan website di alam sutera",
    "jasa pembuatan website di bsd",
    "jasa pembuatan website di bsd city",
    "jasa pembuatan website di serpong",
    "jasa pembuatan website di serpong city",
    "jasa pembuatan website di serpong garden",
    "jasa pembuatan website di serpong garden city",
    "jasa pembuatan website di serpong garden city tangerang",
    "jasa pembuatan website di serpong tangerang",
    "jasa pembuatan website di serpong city tangerang",
    "jasa pembuatan website di serpong garden tangerang",
    "jasa pembuatan website di serpong garden city tangerang",
    "jasa pembuatan website di serpong garden city tangerang banten",
    "jasa pembuatan website di serpong tangerang banten",
    "jasa pembuatan website di serpong city tangerang banten",
    "jasa pembuatan website di serpong garden tangerang banten",
    "jasa pembuatan website di serpong garden city tangerang banten",
    "developer di alam sutera",
    "developer di bsd",
    "developer di bsd city",
    "developer di serpong",
    "developer di serpong city",
    "developer di serpong garden",
    "developer di serpong garden city",
    "developer di serpong garden city tangerang",
    "developer di serpong tangerang",
    "developer di serpong city tangerang",
    "developer di serpong garden tangerang",
    "developer di serpong garden city tangerang",
    "developer di serpong garden city tangerang banten",
    "developer di serpong tangerang banten",
    "developer di serpong city tangerang banten",
    "developer di serpong garden tangerang banten",
    "jasa pembuatan website di indonesia",
    "jasa pembuatan website di alam sutera",
    "jasa pembuatan website di bsd",
    "jasa pembuatan website di bsd city",
    "jasa pembuatan otomatisasi di indonesia",
    "jasa pembuatan otomatisasi di alam sutera",
    "jasa pembuatan otomatisasi di bsd",
    "jasa pembuatan otomatisasi di bsd city",
    "jasa pembuatan otomatisasi di serpong",
    "jasa pembuatan otomatisasi di serpong city",
    "jasa pembuatan otomatisasi di serpong garden",
    "jasa pembuatan otomatisasi di serpong garden city",
    "jasa pembuatan otomatisasi di serpong garden city tangerang",
    "jasa pembuatan otomatisasi di serpong tangerang",
    "jasa pembuatan otomatisasi di serpong city tangerang",
    "jasa pembuatan otomatisasi di serpong garden tangerang",
    "jasa pembuatan otomatisasi di serpong garden city tangerang",
    "jasa pembuatan otomatisasi di serpong garden city tangerang banten",
    "jasa pembuatan otomatisasi di serpong tangerang banten",
    "jasa pembuatan otomatisasi di serpong city tangerang banten",
    "jasa pembuatan otomatisasi di serpong garden tangerang",
    "jasa pembuatan otomatisasi di serpong garden city tangerang",
    "jasa pembuatan otomatisasi di serpong garden city tangerang banten",
    "jasa pembuatan otomatisasi di serpong tangerang banten",
    "jasa pembuatan otomatisasi di serpong city tangerang banten",
    "jasa pembuatan otomatisasi di serpong garden tangerang",
    "jasa pembuatan otomatisasi di serpong garden city tangerang",
    "jasa scraping di indonesia",
    "jasa scraping di alam sutera",
    "jasa scraping di bsd",
    "jasa scraping di bsd city",
    "jasa scraping di serpong",
    "jasa scraping di serpong city",
    "jasa scraping di serpong garden",
    "jasa scraping di serpong garden city",
    "jasa scraping di serpong garden city tangerang",
    "jasa scraping di serpong tangerang",
    "jasa scraping di serpong city tangerang",
    "jasa scraping di serpong garden tangerang",
    "jasa scraping di serpong garden city tangerang",
    "jasa scraping di serpong garden city tangerang banten",
    "jasa scraping di serpong tangerang banten",
    "jasa scraping di serpong city tangerang banten",
    "jasa scraping di serpong garden tangerang banten",
    "jasa scraping di serpong garden city tangerang banten",
    "jasa pembuatan website di serpong garden tangerang banten",
    "jasa scraping di serpong tangerang banten",
    "jasa scraping di serpong city tangerang banten",
    "jasa scraping di serpong garden tangerang banten",
    "jasa scraping di serpong garden city tangerang banten",
    "jasa pembuatan website di serpong garden tangerang banten",
    "jasa pembuatan aplikasi di indonesia",
    "jasa pembuatan aplikasi di alam sutera",
    "jasa pembuatan aplikasi di bsd",
    "jasa pembuatan aplikasi di bsd city",
    "jasa pembuatan aplikasi di serpong",
    "jasa pembuatan aplikasi di serpong city",
    "jasa pembuatan aplikasi di serpong garden",
    "jasa pembuatan aplikasi di serpong garden city",
    "jasa pembuatan aplikasi di serpong garden city tangerang",
    "jasa pembuatan aplikasi di serpong tangerang",
    "jasa pembuatan aplikasi di serpong city tangerang",
    "jasa pembuatan aplikasi di serpong garden tangerang",
    "jasa pembuatan aplikasi di serpong garden city tangerang",
    "jasa pembuatan aplikasi di serpong garden city tangerang banten",
    "jasa pembuatan aplikasi di serpong tangerang banten",
    "jasa pembuatan aplikasi di serpong city tangerang banten",
    "jasa pembuatan aplikasi di serpong garden tangerang",
    "jasa pembuatan aplikasi di serpong garden city tangerang",
    "jasa pembuatan aplikasi di serpong garden city tangerang banten",
    "jasa pembuatan aplikasi di serpong tangerang banten",
    "jasa pembuatan aplikasi di serpong city tangerang banten",
    "jasa pembuatan aplikasi di serpong garden tangerang",
    "jasa pembuatan aplikasi di serpong garden city tangerang",
    "jasa pembuatan aplikasi di serpong garden city tangerang banten",
    "jasa buat toko online di indonesia",
    "jasa buat toko online di alam sutera",
    "jasa buat toko online di bsd",
    "jasa buat toko online di bsd city",
    "jasa buat toko online di serpong",
    "jasa buat toko online di serpong city",
    "jasa buat toko online di serpong garden",
    "jasa buat toko online di serpong garden city",
    "jasa buat toko online di serpong garden city tangerang",
    "jasa buat toko online di serpong tangerang",
    "jasa buat toko online di serpong city tangerang",
    "jasa buat toko online di serpong garden tangerang",
    "jasa buat toko online di serpong garden city tangerang",
    "jasa buat toko online di serpong garden city tangerang banten",
    "jasa buat toko online di serpong tangerang banten",
    "jasa buat toko online di serpong city tangerang banten",
    "jasa buat toko online di serpong garden tangerang",
    "jasa buat toko online di serpong garden city tangerang",
    "jasa buat toko online di serpong garden city tangerang banten",
    "jasa buat toko online di serpong tangerang banten",
    "jasa buat toko online di serpong city tangerang banten",
    "jasa buat toko online di serpong garden tangerang",
    "jasa buat toko online di serpong garden city tangerang",
    "jasa buat toko online di serpong garden city tangerang banten",
    "jasa buat toko online di serpong tangerang banten",
    "jasa buat toko online di serpong city tangerang banten",
]